import { Archivo } from "next/font/google";
import "@/styles/globals.css";
import Navbar from "@/components/Navbar";

const archivo = Archivo({
  display: "swap",
  weight: "variable",
  subsets: ["latin"],
  variable: "---font-archivo",
});

export const metadata = {
  title: "United Hearts",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${archivo.variable} antialiased bg-stone-200 text-stone-900`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
